### ISSUE TITLE
Why have the ExcelSerializer constructors that take Worksheets or Workbooks been made non-public?

### ISSUE THREAD

**Issue by paulduran** [youngcm2/CsvHelper.Excel#1]
I'm in the process of upgrading `CsvHelper` and `ClosedXml` and, as a consequence, replacing our `CsvHelper.Excel` with the `CsvHelper.Excel.Core` package that you have produced.

I noticed that in commit: `5ed3a74ea81c302ce39017b2a55efe810788e5e6` you have changed the public constructor signatures to only accept either a file path or a stream, but not allow the ability to pass in an XLWorkbook or XLWorksheet.

Could you please explain the thinking there? We have use cases where we are constructing an excel file with multiple worksheets, each worksheet being populated by CsvHelper with a different configuration/objects. And in the end, we are streaming the result via HTTP.

**Comment by youngcm2** [comment]
I made them private to control the lifecycle.

**Comment by youngcm2** [comment]
@paulduran please try the new version

**Comment by josegomera** [comment]
@youngcm2 any solutions on this?
I have tried to create a spreadsheet with more than 2 worksheets but it seems that the code overrides the same worksheet instead of adding a new one.

![image](https://github.com/youngcm2/CsvHelper.Excel/assets/5961326/8f7d8aea-5a4b-4257-a273-a882e1548f87)
