### ISSUE TITLE
Cell value

### ISSUE THREAD

**Issue by robertovaldesperez** [youngcm2/CsvHelper.Excel#17]
hi @youngcm2 @chinmaykelkar9141 

The value of the cell depends on the currentinfo

Would it be possible to extract the value of the cell from the excel without depending on the currentinfo? For example, there are times when numbers or dates come in different formats but you are interested in extracting the number or date value

**Comment by youngcm2** [comment]
Released 
* [Releases: 27.2.1](https://github.com/youngcm2/CsvHelper.Excel/releases/tag/27.2.1)
* [Nuget: 27.2.1](https://www.nuget.org/packages/CsvHelper.Excel.Core/27.2.1)
