### ISSUE TITLE
Errors that would bubble up while reading a CSV don't happen while reading Excel and library hangs on new ExcelParser initialization

### ISSUE THREAD

**Issue by altmank** [youngcm2/CsvHelper.Excel#2]
Is this a known issue?

**Comment by youngcm2** [comment]
I just released a new beta version on nuget. If you still encounter it. Please post a test file.

**Comment by altmank** [comment]
@youngcm2 Thanks, I can't upgrade to the latest CSVHelper version yet that your new deployment requires. They have basically no documentation on how to upgrade to that major version. Once that is available I'll try it out with some problem files.

**Comment by youngcm2** [comment]
Closing for now
