### ISSUE TITLE
Update needed to work with CsvHelper v27

### ISSUE THREAD

**Issue by CaiusJard** [youngcm2/CsvHelper.Excel#25]
**Describe the bug**
v27 of CSvH's IParser (current version at time of writing, maybe earlier versions too) interface insists on property `public string Delimiter`, which is not implemented

**To Reproduce**
1. Try to use vLatest CsvHelper.Excel with v27+ of CsvH

**Expected behavior**
Works without throwing exception due to missing member

**Versions (please complete the following information):**
 - CSVHelper: 27
 - CSVHelper.Excel.Core: 22

**Additional context**

Just needs `public string Delimiter => ",";` or similar adding to ExcelParser. It's not used, as far as I can see.. just needs to exist

**Comment by youngcm2** [comment]
Released 
* [Releases: 27.2.1](https://github.com/youngcm2/CsvHelper.Excel/releases/tag/27.2.1)
* [Nuget: 27.2.1](https://www.nuget.org/packages/CsvHelper.Excel.Core/27.2.1)
