### ISSUE TITLE
ExcelWriter - Allow CSV Configuration?

### ISSUE THREAD

**Issue by altmank** [youngcm2/CsvHelper.Excel#7]
Hello,

It looks like the ExcelWriter constructor that allows for a specified CsvConfiguration is private, is this intentional to prevent some issue? If it doesn't break anything, can you allow public access to this constructor so that the Excel output can be configured?

**Comment by youngcm2** [comment]
I did hide it on purpose. Those settings have no bearing on the excel writer.
